apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-mongo-deployment
  namespace: ticketing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-mongo
  template:
    metadata:
      labels:
        app: ticket-mongo
    spec:
      containers:
        - name: ticket-mongo
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-mongo-service
  namespace: ticketing-app
spec:
  type: ClusterIP
  selector:
    app: ticket-mongo
  ports:
    - name: ticket-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017