apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: monitoring
spec:
  selector: 
    app: kibana
  type: ClusterIP  
  ports:
    - name: service
      protocol: TCP
      port: 8080
      targetPort: 5601