apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistence-volume-elasticsearch-storage-0
  namespace: monitoring
spec:
  storageClassName: elasticsearch-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/persistentvolume/elasticsearch-storage-0"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistence-volume-elasticsearch-storage-1
  namespace: monitoring
spec:
  storageClassName: elasticsearch-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/persistentvolume/elasticsearch-storage-1"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistence-volume-elasticsearch-storage-2
  namespace: monitoring
spec:
  storageClassName: elasticsearch-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/persistentvolume/elasticsearch-storage-2"
    type: DirectoryOrCreate