apiVersion: v1
kind: Service
metadata:
  name: kibana-nodeport
  namespace: monitoring
spec:
  selector: 
    app: kibana
  type: NodePort  
  ports:
    - name: service
      protocol: TCP
      port: 8080
      targetPort: 5601
      nodePort: 31000