apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: ticket-service-queue-binding
  namespace: ticketing-app
spec:
  source: ticketing-app-exchange    # an existing exchange
  destination: ticket-service-queue # an existing queue
  destinationType: queue            # can be 'queue' or 'exchange'
  routingKey: "order.#"
  vhost: ticketing-app-vhost 
  rabbitmqClusterReference:
    name: rabbitmq-cluster