name: deploy-infra-k8s-manifests

on: 
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing-app-k8-cluster
      # - run: kubectl apply -f infra/k8s/pre-requisite-manifests --recursive
      # - run: sleep 30
      # - run: kubectl apply -f infra/k8s/pre-requisite-manifests-prod-digital-ocean
      # - run: sleep 30
      - run: kubectl apply -f infra/k8s/application-manifests --recursive
      - run: sleep 30
      - run: kubectl apply -f infra/k8s/application-manifests-prod